// Solar Icons (Bold Duotone): kräftige zweifarbige Flächen, die die Textfarbe übernehmen. Jedes Icon wird einzeln importiert.
import { Icon as Iconify, type IconifyIcon } from '@iconify/react/offline';
import checkData from '@iconify-icons/material-symbols/check-rounded';
import plusData from '@iconify-icons/material-symbols/add-rounded';
import minusData from '@iconify-icons/material-symbols/remove-rounded';
import xData from '@iconify-icons/material-symbols/close-rounded';
import runIconData from '@iconify-icons/solar/running-round-bold-duotone';
import strengthIconData from '@iconify-icons/solar/dumbbell-large-bold-duotone';
import mobilityIconData from '@iconify-icons/solar/stretching-round-bold-duotone';
import volleyIconData from '@iconify-icons/solar/volleyball-bold-duotone';
import restIconData from '@iconify-icons/solar/moon-sleep-bold-duotone';
import moonData from '@iconify-icons/solar/moon-bold-duotone';
import calendarDaysData from '@iconify-icons/solar/calendar-bold-duotone';
import listChecksData from '@iconify-icons/solar/checklist-minimalistic-bold-duotone';
import chartColumnData from '@iconify-icons/solar/chart-2-bold-duotone';
import bookOpenData from '@iconify-icons/solar/book-2-bold-duotone';
import settings2Data from '@iconify-icons/solar/settings-bold-duotone';
import circleCheckData from '@iconify-icons/solar/check-circle-bold-duotone';
import circleXData from '@iconify-icons/solar/close-circle-bold-duotone';
import circleDotData from '@iconify-icons/solar/circle-dot-bold-duotone';
import circleDashedData from '@iconify-icons/solar/circle-dashed-bold-duotone';
import triangleAlertData from '@iconify-icons/solar/danger-triangle-bold-duotone';
import chevronDownData from '@iconify-icons/solar/alt-arrow-down-bold-duotone';
import chevronLeftData from '@iconify-icons/solar/alt-arrow-left-bold-duotone';
import chevronRightData from '@iconify-icons/solar/alt-arrow-right-bold-duotone';
import playData from '@iconify-icons/solar/play-bold-duotone';
import pauseData from '@iconify-icons/solar/pause-bold-duotone';
import infoData from '@iconify-icons/solar/info-circle-bold-duotone';
import playCircleData from '@iconify-icons/solar/play-circle-bold-duotone';
import pencilData from '@iconify-icons/solar/pen-bold-duotone';
import trash2Data from '@iconify-icons/solar/trash-bin-trash-bold-duotone';
import downloadData from '@iconify-icons/solar/download-minimalistic-bold-duotone';
import uploadData from '@iconify-icons/solar/upload-minimalistic-bold-duotone';
import refreshCwData from '@iconify-icons/solar/refresh-bold-duotone';
import rotateCcwData from '@iconify-icons/solar/undo-left-round-bold-duotone';
import externalLinkData from '@iconify-icons/solar/square-arrow-right-up-bold-duotone';
import calendarPlusData from '@iconify-icons/solar/calendar-add-bold-duotone';
import sparklesData from '@iconify-icons/solar/magic-stick-3-bold-duotone';
import flagData from '@iconify-icons/solar/flag-bold-duotone';
import pinData from '@iconify-icons/solar/pin-bold-duotone';
import scaleData from '@iconify-icons/solar/scale-bold-duotone';
import sunData from '@iconify-icons/solar/sun-2-bold-duotone';
import monitorData from '@iconify-icons/solar/monitor-bold-duotone';
import type { FunctionComponent, SVGProps } from 'react';

/** Icon der App */
export type AppIcon = FunctionComponent<Pick<SVGProps<SVGSVGElement>, 'className' | 'style' | 'aria-hidden' | 'aria-label'>>;

const icon = (data: IconifyIcon): AppIcon => props => <Iconify icon={data} {...props} />;

// Schlichte Striche (Haken, Plus, Minus, Kreuz) gibt es bei Solar nicht zweifarbig – daher Material Symbols
export const Check = icon(checkData);
export const Plus = icon(plusData);
export const Minus = icon(minusData);
export const X = icon(xData);

export const RunIcon = icon(runIconData);
export const StrengthIcon = icon(strengthIconData);
export const MobilityIcon = icon(mobilityIconData);
export const VolleyIcon = icon(volleyIconData);
export const RestIcon = icon(restIconData);
export const Moon = icon(moonData);
export const CalendarDays = icon(calendarDaysData);
export const ListChecks = icon(listChecksData);
export const ChartColumn = icon(chartColumnData);
export const BookOpen = icon(bookOpenData);
export const Settings2 = icon(settings2Data);
export const CircleCheck = icon(circleCheckData);
export const CircleX = icon(circleXData);
export const CircleDot = icon(circleDotData);
export const CircleDashed = icon(circleDashedData);
export const TriangleAlert = icon(triangleAlertData);
export const ChevronDown = icon(chevronDownData);
export const ChevronLeft = icon(chevronLeftData);
export const ChevronRight = icon(chevronRightData);
export const Play = icon(playData);
export const Pause = icon(pauseData);
export const Info = icon(infoData);
export const PlayCircle = icon(playCircleData);
export const Pencil = icon(pencilData);
export const Trash2 = icon(trash2Data);
export const Download = icon(downloadData);
export const Upload = icon(uploadData);
export const RefreshCw = icon(refreshCwData);
export const RotateCcw = icon(rotateCcwData);
export const ExternalLink = icon(externalLinkData);
export const CalendarPlus = icon(calendarPlusData);
export const Sparkles = icon(sparklesData);
export const Flag = icon(flagData);
export const Pin = icon(pinData);
export const Scale = icon(scaleData);
export const Sun = icon(sunData);
export const Monitor = icon(monitorData);
